version: '3'

volumes:
  db-data: {}

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ".:/var/www"
    depends_on:
      - database

  database:
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'budget'
      MYSQL_USER: 'budget'
      MYSQL_PASSWORD: 'test'
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql:rw
